# Generated by Django 5.0.3 on 2024-03-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('plan', models.CharField(choices=[('Basic', 'Basic'), ('Platnum', 'Platnum'), ('Elite', 'Elite'), ('Exclusive', 'Exclusive')], max_length=20)),
                ('wallet_address', models.CharField(max_length=100)),
                ('amount', models.IntegerField(null=True)),
            ],
        ),
    ]
